version: '2'
services:
  db:
    container_name: booster.db
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    networks:
      - booster
  pma:
    container_name: booster.pma
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    links:
      - db
    ports:
      - $PMA_PORT:80
    networks:
      - booster
  backend:
    container_name: booster.backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - composer
    entrypoint: "php bin/console server:run *:8000"
    ports:
      - $BACKEND_PORT:8000
    volumes:
      - ./backend/src:/var/www/symfony
    networks:
      - booster
  composer:
    restart: 'no'
    image: composer/composer:php7
    command: install
    volumes:
      - ./backend/src:/app
  frontend:
    container_name: booster.frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    entrypoint: "npm run start"
    ports:
      - $FRONT_REACT_PORT:$REACT_PORT
    volumes:
      - ./front/src:/usr/src/app
    networks:
      - booster
  mongo:
    container_name: booster.mongo
    image: mongo:3
    volumes:
      - ./volumes/mongo/data:/data/db
    networks:
      - booster
  elasticsearch:
    container_name: booster.elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    volumes:
      - ./volumes/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network_host
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 1g
    networks:
      - booster
  graylog:
    container_name: booster.graylog
    image: graylog/graylog:2.3.2-1
    volumes:
      - ./volumes/graylog/journal:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
    environment:
      - GRAYLOG_PASSWORD_SECRET=$GRAYLOG_PASSWORD_SECRET
      # PASSWORD:
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_WEB_ENDPOINT_URI=http://127.0.0.1:9000/api
      - GRAYLOG_ELASTIC_SEARCH_HOSTS=http://elasticsearch:9300
    links:
      - mongo
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    networks:
      - booster

networks:
  booster:
    external:
      name: booster
